### ISSUE TITLE
Failed in parsing email thread

### ISSUE THREAD

**Issue by perajovic** [willdurand/EmailReplyParser#27]
I just found some real world scenario where this lib fails to preserve formatting.
Basically the problem is where we have a whole email thread as a content. All new lines are replaced with one space [here](https://github.com/willdurand/EmailReplyParser/blob/master/src/EmailReplyParser/Parser/EmailParser.php#L53).
I made in commit https://github.com/perajovic/EmailReplyParser/commit/79aebccd4dac497066b5a151dc19906b9b2025c6 failing test with an example.
Here is also a diff from test:
```
1) EmailReplyParser\Tests\Parser\EmailParserTest::testEmailThreadPreservesNewLines
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'On Nov 21, 2014, at 10:18, John Doe <john@doe123.com> wrote:
-
-> Ok. Thanks.
->
-> On Nov 21, 2014, at 9:26, Jim Beam <jim@beam123.com> wrote:
->
->>> On Nov 20, 2014, at 11:03 AM, John Doe <john@doe123.com> wrote:
+'On Nov 21, 2014, at 10:18, John Doe <john@doe123.com> wrote:  > Ok. Thanks. > > On Nov 21, 2014, at 9:26, Jim Beam <jim@beam123.com> wrote: > >>> On Nov 20, 2014, at 11:03 AM, John Doe <john@doe123.com> wrote:
 >>>
 >>> if you take a look at a short video from attachment, why full-typed filename does not stay in CMD+T pane?
 >>> When I type last character, it is not shown anymore.
 >>
 >> We think we’ve tracked down the cause of this issue, write back if you see the issue after the next update. (Which will be out shortly.)
 >>
 >> --
 >> Jim Beam – Acme Corp
 >>
 >'
```

I'm aware that with this [line](https://github.com/willdurand/EmailReplyParser/blob/master/src/EmailReplyParser/Parser/EmailParser.php#L53) we can normalize some poorly formatted emails, but here this is not the case. 

I hope I can fix this issue later today, but if someone have any idea how to do this right now, please write a comment.

**Comment by likeuntomurphy** [comment]
I was having this problem as well when a fragment contains multiple headers. The problem appears to be  that the quote header regular expressions are greedy and matching too much. Making them lazy fixes my immediate problem, and all tests — including the one @perajovic referenced above — pass.

**Comment by tomsommer** [comment]
Why not just remove the "s" modifier, or add the "U" modifier?
