### ISSUE TITLE
Does this work with parsing HTML mail?

### ISSUE THREAD

**Issue by keithslater** [willdurand/EmailReplyParser#46]
I've tested it with text/html mail and it seems to return the full email when I call parseReply. My email looks like this-

`Test reply y2e0g41 <br /><br /> <br /><p>On June 15, 2016 at 9:47:14 AM, Keith Slater (projectstest+y2e0g41@test.com) wrote:</p> `

`test sdfdsfdsf `

**Comment by willdurand** [comment]
Nope, it is used _for parsing plain text email content_ only.
