### ISSUE TITLE
Create a new release on Packagist.org

### ISSUE THREAD

**Issue by tsmes** [willdurand/EmailReplyParser#55]
The current release on [Packagist.org](https://packagist.org/packages/willdurand/email-reply-parser) is 2.5 and is from 2016-02-25. It seems like a lot of stuff has been added to this library since then but it's not available unless you pull directly from the repository.

Is it possible to tag a new release in the nearest future?

**Comment by willdurand** [comment]
Hi @tsmes, [2.6.0](https://github.com/willdurand/EmailReplyParser/releases/tag/2.6.0) is out!
