### ISSUE TITLE
EmailReplyParser::parseReply issue

### ISSUE THREAD

**Issue by Nuranto** [willdurand/EmailReplyParser#77]
Hello,

I just got a bug on `EmailReplyParser::parseReply`. In some specific case, the reply is truncated in the middle.

I tried to reduce at maximum a case, here it is : 

```
Bonjour ​Test​,

​Text paragraph 1​


Le paragraphe qui pose problème.

​Text paragraph 2​


- Le 2021-04-09 23:25, ​Test a écrit :
``` 

The correct result should be : 

```
Bonjour ​Test​,

​Text paragraph 1​


Le paragraphe qui pose problème.

​Text paragraph 2​
```

The current result is : 
```
Bonjour ​Test​,

        ​Text paragraph 1​
```

Context : 
* This is french. If I remove the first "Le" : problem solved. If I remove "écrit" : problem solved.
* `Le paragraphe qui pose problème` means `The paragraph which provoke issue`. 
* `Le 2021-04-09 23:25, ​Test a écrit :` means `On 2021-04-09 23:25, ​Test wrote :`

So the issue is here : 
```
'/^\s*(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit(\s|\xc2\xa0):)$/ms', // Le DATE, NAME <EMAIL> a écrit :
```

If I change it to have the same format as the english work : problem half solved (not truncated).
```
'/^\s*(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit:)$/ms', // Le DATE, NAME <EMAIL> a écrit :
```

But I think that `(\s|\xc2\xa0)` was here for some reason ? @Spone ?

see also : 
https://github.com/willdurand/EmailReplyParser/commit/e888d795f277916ec62c2e812b9a10a9614682e8#diff-5e5f4da6cc02b271ae11752a0b5e45ecb842d913728f7b7d9756d88d9219a0f8
https://github.com/willdurand/EmailReplyParser/commit/b71d9983c07b0455cb5b9727b90642a32bc11ae0#diff-5e5f4da6cc02b271ae11752a0b5e45ecb842d913728f7b7d9756d88d9219a0f8

**Comment by Nuranto** [comment]
What about 

`/^\s*(Le(?:(?!^>?.*\s*Le\b|\bécrit(\s|\xc2\xa0)*:).){0,1000}écrit(\s|\xc2\xa0)*:)$/ms` ?

Modifications : 
# The space after `écrit` should be optionnal
# That space should be replicated to the subquery
# I don't understand that part : `^>*`  ?  Isn't `^>?.*` more accurate ?

It seems to work for my example at least.

Is there some unit test in this package ?

**Comment by Spone** [comment]
Hi @Nuranto!

The problem in your case it probably the `-` at the beginning of this line:

```
- Le 2021-04-09 23:25, ​Test a écrit :
```

Do you know why it's there?

Here is a fix that would make the regex match your specific case:

```
/^-+?\s*(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit(\s|\xc2\xa0)?:)$/ms
```

Try in on Regexr: https://regexr.com/5qha2

**Comment by Nuranto** [comment]
Thank you for your answer @Spone 

After some investigation, it seems that it is the way of doing of https://zimbra.free.fr/ which is a french webmail...

Your solution seems to work for that particular case, but it should be generic. And most of all, the regex should not failed like this whatever the source string is. 
And I think it is a global issue, not only the FR regexp.

I don't understand the purpose of subpattern, probably because I'm not used to subpatterns, but why don't use something like that :

**Comment by Nuranto** [comment]
Thank you for your answer @Spone 

After some investigation, it seems that it is the way of doing of https://zimbra.free.fr/ which is a french webmail...

Your solution seems to work for that particular case, but it should be generic. And most of all, the regex should not failed like this whatever the source string is. 
And I think it is a global issue, not only the FR regexp.

What about something like this : 
```
/^.{0,5}(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit(\s|\xc2\xa0)?:)$/m
```
?

**Comment by Spone** [comment]
> What about something like this :
> 
> ```
> /^.{0,5}(Le\b(?:(?!^>*\s*Le\b|\bécrit(\s|\xc2\xa0)?:).){0,1000}écrit(\s|\xc2\xa0)?:)$/m
> ```
> 
> ?

It seems to work. Have you tried running the tests with this change?

I'm not sure why the current regexes use the `s` flag. Maybe @willdurand can shed some light?

**Comment by Nuranto** [comment]
Yes test pass. For that regex at least.
For EN regex it seems more complicated (see my PR).

I wonder if it wouldn't be better to have only one regexep template for that, and an array for locales (`[ ['Le', 'écrit'], ['On', 'wrote'] ]`), so the regexp and the tests can be standardized.
