### ISSUE TITLE
Inline Replies

### ISSUE THREAD

**Issue by cjsfj** [willdurand/EmailReplyParser#89]
Is there any recommendation on how to handle inline replies?

Often the quoted text may have replies in-between quotes.. answering the specific question within quote fragment. Hoping to find a way to retain those inline quotes but then parse and discard all the junk at the end.

Thanks!

CJ

**Comment by willdurand** [comment]
I think we can detect quoted paragraphs but not much more unfortunately.

**Comment by cjsfj** [comment]
Thanks Will.

I ended up just looping through the fragments to ensure that I only keep up until the last visible fragment and then discard the rest. Most of the time that ends up being the original quoted reply.

CJ
